/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface UfeAccountApp {
        "identity": string;
        "userName": string;
    }
    interface UfeAvatar {
        /**
          * The first name
         */
        "email": string;
        /**
          * The middle name
         */
        "size": number;
    }
}
declare global {
    interface HTMLUfeAccountAppElement extends Components.UfeAccountApp, HTMLStencilElement {
    }
    var HTMLUfeAccountAppElement: {
        prototype: HTMLUfeAccountAppElement;
        new (): HTMLUfeAccountAppElement;
    };
    interface HTMLUfeAvatarElement extends Components.UfeAvatar, HTMLStencilElement {
    }
    var HTMLUfeAvatarElement: {
        prototype: HTMLUfeAvatarElement;
        new (): HTMLUfeAvatarElement;
    };
    interface HTMLElementTagNameMap {
        "ufe-account-app": HTMLUfeAccountAppElement;
        "ufe-avatar": HTMLUfeAvatarElement;
    }
}
declare namespace LocalJSX {
    interface UfeAccountApp {
        "identity"?: string;
        "userName"?: string;
    }
    interface UfeAvatar {
        /**
          * The first name
         */
        "email"?: string;
        /**
          * The middle name
         */
        "size"?: number;
    }
    interface IntrinsicElements {
        "ufe-account-app": UfeAccountApp;
        "ufe-avatar": UfeAvatar;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ufe-account-app": LocalJSX.UfeAccountApp & JSXBase.HTMLAttributes<HTMLUfeAccountAppElement>;
            "ufe-avatar": LocalJSX.UfeAvatar & JSXBase.HTMLAttributes<HTMLUfeAvatarElement>;
        }
    }
}
