/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Router } from "stencil-router-v2";
export { Router } from "stencil-router-v2";
export namespace Components {
    interface UfeAppRouter {
        "homeComponent": string;
    }
    interface UfeApplicationCards {
        "router": Router;
        "selector": string;
    }
    interface UfeApplicationsList {
        "router": Router;
        "selector": string;
    }
    interface UfeContext {
        "context": string;
        "data": {
    [key: string]: any
  };
        "extraAttributes": { [key: string]: string};
        "selector": string;
    }
    interface UfeDefaultShell {
    }
    interface UfeFrame {
        "height": string;
        "src": string;
        "width": string;
    }
}
declare global {
    interface HTMLUfeAppRouterElement extends Components.UfeAppRouter, HTMLStencilElement {
    }
    var HTMLUfeAppRouterElement: {
        prototype: HTMLUfeAppRouterElement;
        new (): HTMLUfeAppRouterElement;
    };
    interface HTMLUfeApplicationCardsElement extends Components.UfeApplicationCards, HTMLStencilElement {
    }
    var HTMLUfeApplicationCardsElement: {
        prototype: HTMLUfeApplicationCardsElement;
        new (): HTMLUfeApplicationCardsElement;
    };
    interface HTMLUfeApplicationsListElement extends Components.UfeApplicationsList, HTMLStencilElement {
    }
    var HTMLUfeApplicationsListElement: {
        prototype: HTMLUfeApplicationsListElement;
        new (): HTMLUfeApplicationsListElement;
    };
    interface HTMLUfeContextElement extends Components.UfeContext, HTMLStencilElement {
    }
    var HTMLUfeContextElement: {
        prototype: HTMLUfeContextElement;
        new (): HTMLUfeContextElement;
    };
    interface HTMLUfeDefaultShellElement extends Components.UfeDefaultShell, HTMLStencilElement {
    }
    var HTMLUfeDefaultShellElement: {
        prototype: HTMLUfeDefaultShellElement;
        new (): HTMLUfeDefaultShellElement;
    };
    interface HTMLUfeFrameElement extends Components.UfeFrame, HTMLStencilElement {
    }
    var HTMLUfeFrameElement: {
        prototype: HTMLUfeFrameElement;
        new (): HTMLUfeFrameElement;
    };
    interface HTMLElementTagNameMap {
        "ufe-app-router": HTMLUfeAppRouterElement;
        "ufe-application-cards": HTMLUfeApplicationCardsElement;
        "ufe-applications-list": HTMLUfeApplicationsListElement;
        "ufe-context": HTMLUfeContextElement;
        "ufe-default-shell": HTMLUfeDefaultShellElement;
        "ufe-frame": HTMLUfeFrameElement;
    }
}
declare namespace LocalJSX {
    interface UfeAppRouter {
        "homeComponent"?: string;
    }
    interface UfeApplicationCards {
        "router"?: Router;
        "selector"?: string;
    }
    interface UfeApplicationsList {
        "router"?: Router;
        "selector"?: string;
    }
    interface UfeContext {
        "context"?: string;
        "data"?: {
    [key: string]: any
  };
        "extraAttributes"?: { [key: string]: string};
        "selector"?: string;
    }
    interface UfeDefaultShell {
    }
    interface UfeFrame {
        "height"?: string;
        "src"?: string;
        "width"?: string;
    }
    interface IntrinsicElements {
        "ufe-app-router": UfeAppRouter;
        "ufe-application-cards": UfeApplicationCards;
        "ufe-applications-list": UfeApplicationsList;
        "ufe-context": UfeContext;
        "ufe-default-shell": UfeDefaultShell;
        "ufe-frame": UfeFrame;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ufe-app-router": LocalJSX.UfeAppRouter & JSXBase.HTMLAttributes<HTMLUfeAppRouterElement>;
            "ufe-application-cards": LocalJSX.UfeApplicationCards & JSXBase.HTMLAttributes<HTMLUfeApplicationCardsElement>;
            "ufe-applications-list": LocalJSX.UfeApplicationsList & JSXBase.HTMLAttributes<HTMLUfeApplicationsListElement>;
            "ufe-context": LocalJSX.UfeContext & JSXBase.HTMLAttributes<HTMLUfeContextElement>;
            "ufe-default-shell": LocalJSX.UfeDefaultShell & JSXBase.HTMLAttributes<HTMLUfeDefaultShellElement>;
            "ufe-frame": LocalJSX.UfeFrame & JSXBase.HTMLAttributes<HTMLUfeFrameElement>;
        }
    }
}
