/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Router } from "stencil-router-v2";
export namespace Components {
    interface UfeApplicationCards {
        "router": Router;
        "selector": string | {[label:string]: string};
    }
    interface UfeApplicationsList {
        "router": Router;
        "selector": string | {[label:string]: string};
    }
    interface UfeDefaultShell {
    }
    interface UfeFrame {
        "height": string;
        "src": string;
        "width": string;
    }
}
declare global {
    interface HTMLUfeApplicationCardsElement extends Components.UfeApplicationCards, HTMLStencilElement {
    }
    var HTMLUfeApplicationCardsElement: {
        prototype: HTMLUfeApplicationCardsElement;
        new (): HTMLUfeApplicationCardsElement;
    };
    interface HTMLUfeApplicationsListElement extends Components.UfeApplicationsList, HTMLStencilElement {
    }
    var HTMLUfeApplicationsListElement: {
        prototype: HTMLUfeApplicationsListElement;
        new (): HTMLUfeApplicationsListElement;
    };
    interface HTMLUfeDefaultShellElement extends Components.UfeDefaultShell, HTMLStencilElement {
    }
    var HTMLUfeDefaultShellElement: {
        prototype: HTMLUfeDefaultShellElement;
        new (): HTMLUfeDefaultShellElement;
    };
    interface HTMLUfeFrameElement extends Components.UfeFrame, HTMLStencilElement {
    }
    var HTMLUfeFrameElement: {
        prototype: HTMLUfeFrameElement;
        new (): HTMLUfeFrameElement;
    };
    interface HTMLElementTagNameMap {
        "ufe-application-cards": HTMLUfeApplicationCardsElement;
        "ufe-applications-list": HTMLUfeApplicationsListElement;
        "ufe-default-shell": HTMLUfeDefaultShellElement;
        "ufe-frame": HTMLUfeFrameElement;
    }
}
declare namespace LocalJSX {
    interface UfeApplicationCards {
        "router"?: Router;
        "selector"?: string | {[label:string]: string};
    }
    interface UfeApplicationsList {
        "router"?: Router;
        "selector"?: string | {[label:string]: string};
    }
    interface UfeDefaultShell {
    }
    interface UfeFrame {
        "height"?: string;
        "src"?: string;
        "width"?: string;
    }
    interface IntrinsicElements {
        "ufe-application-cards": UfeApplicationCards;
        "ufe-applications-list": UfeApplicationsList;
        "ufe-default-shell": UfeDefaultShell;
        "ufe-frame": UfeFrame;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ufe-application-cards": LocalJSX.UfeApplicationCards & JSXBase.HTMLAttributes<HTMLUfeApplicationCardsElement>;
            "ufe-applications-list": LocalJSX.UfeApplicationsList & JSXBase.HTMLAttributes<HTMLUfeApplicationsListElement>;
            "ufe-default-shell": LocalJSX.UfeDefaultShell & JSXBase.HTMLAttributes<HTMLUfeDefaultShellElement>;
            "ufe-frame": LocalJSX.UfeFrame & JSXBase.HTMLAttributes<HTMLUfeFrameElement>;
        }
    }
}
