/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Router } from "stencil-router-v2";
export namespace Components {
    interface AppHome {
    }
    interface AppProfile {
    }
    interface UfeApplicationsList {
        "router": Router;
        "selector": string | {[label:string]: string};
    }
    interface UfeDefaultShell {
    }
}
declare global {
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {
    }
    var HTMLAppProfileElement: {
        prototype: HTMLAppProfileElement;
        new (): HTMLAppProfileElement;
    };
    interface HTMLUfeApplicationsListElement extends Components.UfeApplicationsList, HTMLStencilElement {
    }
    var HTMLUfeApplicationsListElement: {
        prototype: HTMLUfeApplicationsListElement;
        new (): HTMLUfeApplicationsListElement;
    };
    interface HTMLUfeDefaultShellElement extends Components.UfeDefaultShell, HTMLStencilElement {
    }
    var HTMLUfeDefaultShellElement: {
        prototype: HTMLUfeDefaultShellElement;
        new (): HTMLUfeDefaultShellElement;
    };
    interface HTMLElementTagNameMap {
        "app-home": HTMLAppHomeElement;
        "app-profile": HTMLAppProfileElement;
        "ufe-applications-list": HTMLUfeApplicationsListElement;
        "ufe-default-shell": HTMLUfeDefaultShellElement;
    }
}
declare namespace LocalJSX {
    interface AppHome {
    }
    interface AppProfile {
    }
    interface UfeApplicationsList {
        "router"?: Router;
        "selector"?: string | {[label:string]: string};
    }
    interface UfeDefaultShell {
    }
    interface IntrinsicElements {
        "app-home": AppHome;
        "app-profile": AppProfile;
        "ufe-applications-list": UfeApplicationsList;
        "ufe-default-shell": UfeDefaultShell;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-profile": LocalJSX.AppProfile & JSXBase.HTMLAttributes<HTMLAppProfileElement>;
            "ufe-applications-list": LocalJSX.UfeApplicationsList & JSXBase.HTMLAttributes<HTMLUfeApplicationsListElement>;
            "ufe-default-shell": LocalJSX.UfeDefaultShell & JSXBase.HTMLAttributes<HTMLUfeDefaultShellElement>;
        }
    }
}
